ktor:
  deployment:
    port: 8001

  application:
    modules:
      - com.github.sn0wo2.ApplicationKt.module

  server:
    requestQueueLimit: 16
    maxRequestSize: 2097152
    responseWriteTimeoutSeconds: 10

  encoding:
    charset: "UTF-8"
    force: true

  logging:
    level: "INFO"
    format: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%level] %msg%n"
    console:
      charset: "UTF-8"
    file:
      charset: "UTF-8"
